# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd4502bb29e6f7490f7fd7773bc0984c"
name = "PDF-CONVERTER"
handle = "pdf-converter"
application_url = "https://defined-based-trunk-languages.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "prachanda-test.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_files,read_files,write_themes"

[auth]
redirect_urls = [
  "https://defined-based-trunk-languages.trycloudflare.com/auth/callback",
  "https://defined-based-trunk-languages.trycloudflare.com/auth/shopify/callback",
  "https://defined-based-trunk-languages.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
